# sales-prc-app Configuration

app:
  id: "20734123"
  host: "0.0.0.0"
  port: "8081"
  basePath: "/sales/prc/v1/*"

sales-db-sys-app:
  host: "sales-db-sys-app-90stud.5sc6y6-3.usa-e2.cloudhub.io"
  port: "443"
  basePath: "/sales/db/sys/v1"
  path:
    transaction: "/transaction"
    transactionItems: "/transaction/items"
  responseTimeOut: "10000"