# heritage-exp-app Secure Configuration

sales-db-sys-app:
  client-id: "![uogVxQQefCvjj+GrC+yQTDZfcJPcA8apqsw55wiwDPjlJjqdvlx5Xw==]"
  client-secret: "![dPdnCVn5TR8yEeD5J7pBDKTk8WQo0ixIMJhOAiEXIam7eppk3nvkTA==]"